from django.contrib.auth.models import User
from django.db import models
from baham.models import VehicleModel
admin= User.objects.get(pk=1)
VehicleModel.objects.create(vendor='Toyota', model='Vitz', capacity=4, type='HATCHBACK', created_by=admin).save()
VehicleModel.objects.create(vendor='Toyota', model='Camry', capacity=4, type='SEDAN', created_by=admin).save()
VehicleModel.objects.create(vendor='Toyota', model='Prius', capacity=4, type='SEDAN', created_by=admin).save()
VehicleModel.objects.create(vendor='Honda', model='City', capacity=4, type='SEDAN', created_by=admin).save()
VehicleModel.objects.create(vendor='Honda', model='Civic', capacity=4, type='SEDAN', created_by=admin).save()
VehicleModel.objects.create(vendor='Honda', model='Accord', capacity=4, type='SEDAN', created_by=admin).save()
VehicleModel.objects.create(vendor='Honda', model='Fit', capacity=4, type='HATCHBACK', created_by=admin).save()
VehicleModel.objects.create(vendor='Toyota', model='Vitz', capacity=4, type='HATCHBACK', created_by=admin). save()
VehicleModel.objects.create(vendor='Toyota', model='Passo', capacity=4, type='HATCHBACK', created_by=admin).save()
VehicleModel.objects.create(vendor='Suzuki', model='Mehran', capacity=4, type='HATCHBACK', created_by=admin). save()
VehicleModel.objects.create(vendor='Suzuki', model='Wagon R', capacity=4, type='HATCHBACK', created_by=admin).save()
VehicleModel.objects.create(vendor='Suzuki', model='Alto', capacity=4, type='HATCHBACK', created_by=admin).save()
VehicleModel.objects.create(vendor='Suzuki', model='Cultus', capacity=4, type='HATCHBACK', created_by=admin).save()
VehicleModel.objects.create(vendor='Suzuki', model='Swift', capacity=4, type='HATCHBACK', created_by=admin).save()
VehicleModel.objects.create(vendor='Hyundai', model='Santro', capacity=4, type='HATCHBACK', created_by=admin).save()
VehicleModel.objects.create(vendor='Daihatsu', model='Mira', capacity=4, type='HATCHBACK', created_by=admin).save()
VehicleModel.objects.create(vendor='Toyota', model='Hilux', capacity=9, type='SUV', created_by=admin).save()
VehicleModel.objects.create(vendor='Toyota', model='Land Cruiser', capacity=6, type='SUV', created_by=admin).save()
VehicleModel.objects.create(vendor='Kia', model='Sportage', capacity=5, type='SUV', created_by=admin).save()
VehicleModel.objects.create(vendor='Honda', model='Vezel', capacity=5, type='SUV', created_by=admin).save()